### ISSUE TITLE
Sentence alignment in MT validation set

### ISSUE THREAD

**Issue by Avmb** [IgnatiusEzeani/IGBONLP#2]
https://github.com/IgnatiusEzeani/IGBONLP/blob/87262a55be7c398fa62925545d897867cf4788b9/ig_en_mt/benchmark_dataset/val.ig

and

https://github.com/IgnatiusEzeani/IGBONLP/blob/87262a55be7c398fa62925545d897867cf4788b9/ig_en_mt/benchmark_dataset/val.en

start aligned with each other but become disaligned by one sentences after some point.

**Comment by IgnatiusEzeani** [comment]
Thanks for letting me know. I will have a look.

**Comment by IgnatiusEzeani** [comment]
This has been corrected and some wrong lines/sentences removed. Hopefully, they should align now.

**Comment by Avmb** [comment]
Thanks
